server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/info}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yml
  mvc: ##required for compatibility with SWAGGER
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true #Enable custom handler for default exceptions
    web: #Enable custom handler for default exceptions
      resources.add-mappings: false
